Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
binary_search = BinarySearch(strategy=IterativeBinarySearchExactMatch())
result = binary_search.find_target([2, 5, 8, 12, 16, 23, 38, 56, 72, 91], 23)
assert result == 5
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[6], line 1[0m
[0;32m----> 1[0m binary_search [38;5;241m=[39m BinarySearch(strategy[38;5;241m=[39m[43mIterativeBinarySearchExactMatch[49m[43m([49m[43m)[49m)
[1;32m      2[0m result [38;5;241m=[39m binary_search[38;5;241m.[39mfind_target([[38;5;241m2[39m, [38;5;241m5[39m, [38;5;241m8[39m, [38;5;241m12[39m, [38;5;241m16[39m, [38;5;241m23[39m, [38;5;241m38[39m, [38;5;241m56[39m, [38;5;241m72[39m, [38;5;241m91[39m], [38;5;241m23[39m)
[1;32m      3[0m [38;5;28;01massert[39;00m result [38;5;241m==[39m [38;5;241m5[39m

[0;31mTypeError[0m: __init__() missing 1 required positional argument: 'strategy'

